# Generated by Django 6.0.2 on 2026-02-10 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Note content')),
                ('is_important', models.BooleanField(default=True, help_text='Mark as important to display on dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='List ingredients line by line')),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('prep_time', models.IntegerField(default=0, help_text='Preparation time in minutes')),
                ('cook_time', models.IntegerField(default=0, help_text='Cooking time in minutes')),
                ('servings', models.IntegerField(default=1, help_text='Number of servings')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('midnight_snack', 'Midnight Snack'), ('any', 'Any Meal')], default='lunch', max_length=20)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular to show on dashboard')),
                ('popularity_score', models.IntegerField(default=0, help_text='Higher score = higher ranking')),
                ('image_url', models.URLField(blank=True, help_text='Recipe image URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('midnight_snack', 'Midnight Snack')], db_index=True, max_length=20)),
                ('custom_meal', models.CharField(blank=True, help_text='Custom meal name if not using a recipe', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or modifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='meals.recipe')),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies', models.TextField(blank=True, help_text='List your food allergies')),
                ('preferences', models.TextField(blank=True, help_text='Your dietary preferences')),
                ('description', models.TextField(blank=True, help_text='Tell us about yourself')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-popularity_score', '-created_at'], name='meals_recip_popular_80dbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_popular'], name='meals_recip_is_popu_c35ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'date'], name='meals_mealp_user_id_3ae197_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'date', 'meal_type'], name='meals_mealp_user_id_6f6b6a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('user', 'date', 'meal_type')},
        ),
    ]
