# Generated by Django 5.2.7 on 2025-10-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='meals_comme_user_id_298252_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='meals_comme_user_id_c83037_idx',
        ),
        migrations.RemoveIndex(
            model_name='mealplan',
            name='meals_mealp_user_id_3ae197_idx',
        ),
        migrations.RemoveIndex(
            model_name='mealplan',
            name='meals_mealp_user_id_6f6b6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='meals_recip_popular_80dbbd_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='meals_recip_is_popu_c35ab4_idx',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any food allergies'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.TextField(blank=True, help_text='Dietary preferences and notes'),
        ),
    ]
