# Generated by Django 5.2.7 on 2025-10-31 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_comment_meals_comme_user_id_298252_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='List any food allergies (e.g., peanuts, shellfish, dairy)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.TextField(blank=True, help_text='Dietary preferences and notes (e.g., vegetarian, low-carb)'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='meals_comme_user_id_298252_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', 'is_important'], name='meals_comme_user_id_c83037_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'date'], name='meals_mealp_user_id_3ae197_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'date', 'meal_type'], name='meals_mealp_user_id_6f6b6a_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-popularity_score', '-created_at'], name='meals_recip_popular_80dbbd_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_popular'], name='meals_recip_is_popu_c35ab4_idx'),
        ),
    ]
