# Generated by Django 5.2.7 on 2025-11-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_userprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='meals_comme_user_id_298252_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='meals_comme_user_id_c83037_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Tell us about yourself'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='List your food allergies'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.TextField(blank=True, help_text='Your dietary preferences'),
        ),
    ]
