# Generated by Django 5.2.7 on 2025-11-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_comment_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('midnight_snack', 'Midnight Snack'), ('any', 'Any Meal')], default='any', max_length=20),
        ),
    ]
