# Generated by Django 5.2.7 on 2025-11-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_recipe_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
    ]
