# Generated by Django 5.2.7 on 2025-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_remove_recipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('midnight_snack', 'Midnight Snack'), ('any', 'Any Meal')], default='lunch', max_length=20),
        ),
    ]
